### ISSUE TITLE
background-position offsets

### ISSUE THREAD

**Issue by siiron** [Ensighten/grunt-spritesmith#142]
First of all – great job on spritesmith! I totally dig it, and currently I’m rewriting our current compass-generated sprites to use grunt-spritesmith instead.
 
I’m still a bit confused about position overrides.
 
I'm struggling to figure out how to override the generated values for natural background-position. By that I mean moving the position relative of the generated values. I'm used to Compass' mixin [sprite-background-position] (http://compass-style.org/reference/compass/utilities/sprites/base/#mixin-sprite-background-position). This can take parameters for offset, but trying this with the mixin `sprite-position` in grunt-spritesmith:
 
    @include sprite-position($icon-foo, 1px, 3px);
 
gives me the following error: "Mixin sprite-position takes 1 argument but 3 were passed".
 
Usually the generated sprite-position is fine, but in some cases I find the need to adjust it by a pixel or two. And often there is only need to do this for a specific icon where other icons in the sprite is fine as they are.

The most common use-case I can think of is when you have an element, e.g. an input field. You'd like to show an icon inside the input and on the right. With the algorithm set to top-down, you'd get a nice vertical column-shaped spritemap. Since the width of the element should not be controlled by the generated sprite (not generating values for width/ height), you'd use:

	@include sprite-image($icon-foo);
 
If you'd add:

	@include sprite-position($icon-foo);

the icon is positioned at the left in the input-field. Not quite what you'd want. You'd like it on the right.

I'd expect something like this:

	@include sprite-position($icon-foo, 100%, $icon-foo-offset-y)

`100%` represents the x-position override (100% to the right), and the `$icon-foo-offset-y` uses the dynamic generated y-position.

How can this be done?

**Comment by twolfson** [comment]
The quick answer is `sprite-position` in `spritesmith` is unintentionally similarly named. While `compass` was part of the inspiration for `spritesmith` (i.e. making spritesheets sane), we did the CSS architecture independently =/

That being said, I am interested in learning about your use case more. I am going to perform some research to see how `compass` implements this feature.

**Comment by twolfson** [comment]
Alright, I am done with my research. Unfortunately, `compass` relies on folders so I cannot point you to my work. As a result, I will attempt to compensate here.

I used 2 test sprites as our images, located in `images/my-icons/` (e.g. `images/my-icons/sprite1.png`):

https://github.com/Ensighten/grunt-spritesmith/blob/5.0.0/src-test/test_files/sprite1.png

https://github.com/Ensighten/grunt-spritesmith/blob/5.0.0/src-test/test_files/sprite3.png

I defined a `sass/screen.scss` via `compass init`. Its contents were:

```scss
@import "compass/utilities/sprites";
@import "my-icons/*.png";

.sprite1 {
  @include my-icons-sprite(sprite1);
}

.sprite3 {
  @include my-icons-sprite(sprite3);
}
```

Upon compilation, it's output was:

![my-icons-sc7a02fc51a](https://cloud.githubusercontent.com/assets/902488/9422803/c402653a-486a-11e5-9e46-f83d8892ad83.png)

```css
/* line 56, my-icons/*.png */
.my-icons-sprite, .sprite1, .sprite3 {
  background-image: url('/images/my-icons-sc7a02fc51a.png');
  background-repeat: no-repeat;
}

/* line 4, ../sass/screen.scss */
.sprite1 {
  background-position: 0 0;
}

/* line 8, ../sass/screen.scss */
.sprite3 {
  background-position: 0 -50px;
}
```

When I moved to using `my-icons-background-position`:

```scss
@import "compass/utilities/sprites";
@import "my-icons/*.png";

.sprite1 {
  @include my-icons-sprite(sprite1);
  @include my-icons-sprite-position(sprite1, 20px, 20px);
}

.sprite3 {
  @include my-icons-sprite(sprite3);
  @include my-icons-sprite-position(sprite1, 20px, 20px);
}
```

I received the same spritesheet with the following CSS:

```css
/* line 56, my-icons/*.png */
.my-icons-sprite, .sprite1, .sprite3 {
  background-image: url('/images/my-icons-sc7a02fc51a.png');
  background-repeat: no-repeat;
}

/* line 4, ../sass/screen.scss */
.sprite1 {
  background-position: 0 0;
  background-position: 20px 20px;
}

/* line 9, ../sass/screen.scss */
.sprite3 {
  background-position: 0 -50px;
  background-position: 20px 20px;
}
```
