### ISSUE TITLE
Provide function to scale sprites

### ISSUE THREAD

**Issue by augbog** [Ensighten/grunt-spritesmith#94]
When generating mixins for sprites, is there a way we can include a mixin that allows you to scale the sprite to different sizes using `background-size`?

I wrote a mixin to do this that works with the mixins generated but was wondering if this could somehow be included in the build? Specifically, I use this for when I have breakpoints and want to scale down sprites. I don't use this for enlarging them really.

``` scss
    @mixin sprite-scale($sprite, $width, $height) {
       $scale-x: nth($sprite, 5) / $width;
       $scale-y: nth($sprite, 6) / $height;
       $sprite-offset-x: nth($sprite, 3) / $scale-x;
       $sprite-offset-y: nth($sprite, 4) / $scale-y;
       $bg-size-x: nth($sprite, 7) / $scale-x;
       $bg-size-y: nth($sprite, 8) / $scale-y;

       @include sprite-image($sprite);
       background-position: $sprite-offset-x + px $sprite-offset-y + px;
       width: $width + px;
       height: $height + px;
       background-size: $bg-size-x + px $bg-size-y + px;
    }
```

I'm kind of new to SASS so if there are ways to optimize this or make it more friendly with the build, let me know! I also haven't thoroughly tested it so any constructive criticism would be appreciated!
